// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfpqvmtvstvwxjqemqkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcHF2bXR2c3R2d3hqcWVtcWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDEwNDQsImV4cCI6MjA1OTIxNzA0NH0.H9wHkuJ2UNyA1x7Wt6DVfswn_wfyadBm0JEbX-aze08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);